[package]
name = "sybot"
authors = [ "Samuel Nösslböck <samuel.noesslboeck@gmail.com>" ]
version = "0.11.0"
description = "Rust library for coordinating components, defining robotic systems and their communication "
edition = "2024"
repository = "https://github.com/SamuelNoesslboeck/sybot"
license-file = "LICENSE"
keywords = [ "framework", "robotics" ]

[lib]
name = "sybot"
path = "src/lib.rs"

[dependencies]
glam = "0.32.1"
serde = { version = "1.0.228", features = ["derive"] }

syact = "0.15.0"
syunit = "0.4.0"